@TenantID=e7e22e48-3b8a-4a70-acb8-a2c86f41bd64
@GrantType=client_credentials
@ClientID=b9907b6a-752c-4d33-886c-417186738198
@ClientSecret=3Wi-.y2lEWH-KcHHZ9V7~Wx7-CVc-.67x~
@Resource=https://management.azure.com

# @name login
POST https://login.microsoftonline.com/{{TenantID}}/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type={{GrantType}}
&client_id={{ClientID}}
&client_secret={{ClientSecret}}
&resource={{Resource}}

###

# @name CreateResourceGroup
@BearerToken={{login.response.body.access_token}}
@SubscriptionID=15f955b8-3425-4681-9277-e54e7f5c14b2
@ResourceGroupName=TestRG-GdR

PUT https://management.azure.com/subscriptions/{{SubscriptionID}}/resourcegroups/{{ResourceGroupName}}?api-version=2020-06-01
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "location": "westeurope"
}